### PR TITLE
Quantify Query Statement for Metropolis Hastings

### PR DESCRIPTION
**Pull request by giulio-zhou**

### CODE REVIEW

**Comment by jxwuyi** [comment]
Do remember to change code correspondingly in Translater.cpp, GibbsTranslator.cpp

@giulio-zhou

**Comment by giulio-zhou** [comment]
Okay, will take a look.

**Comment by giulio-zhou** [comment]
Since GibbsTranslator inherits from Translator, this should only be necessary in Translator, right?

**Comment by jxwuyi** [comment]
@giulio-zhou  GibbsTranslator inherits MHTranslator. I am not sure if it should be modified. So I asked you to check it to make sure.

Actually, we had some design issue when starting developing ***Translator.cpp. So in the current moment, when you change something in a particular translator, you also need to check the implementation in all other translators.

**Comment by giulio-zhou** [comment]
Alright, I'll take a closer look before our meeting this afternoon.

**Comment by giulio-zhou** [comment]
Separated the for loop-specific components into a separate helper function. Was able to figure out which of the variables (`lhs` and `loop_n`) were responsible for the segfault in compilation, but not clear on how to copy them.
Also, while trying to port this over to `Translator.cpp`, I've noticed that `Translator.cpp` doesn't have a lot of the same utility functions; for example, creating pointer method calls. `Translator` also uses `coreClsPrint` rather than `corePrint`, but that should be easy to deal with.

**Comment by tonyduan** [comment]
@jxwuyi Updated this branch to include code used for CP7. Basically I just rebased Giulio's changes on top of my MCMC-Framework branch for CP7 since I need to use his quantify query code.

If you want to merge it in that's fine, otherwise I can ask the folks at Galois to pull from this branch.

**Comment by jxwuyi** [comment]
@tonyduan let's firstly leave this branch here for the moment.

**Comment by jxwuyi** [comment]
@giulio-zhou I see there is another PR called Quantify Query Syntax.

Can you double check why there are two different PR which seem to do the same thing.

**Comment by tonyduan** [comment]
Giulio is correct -- since I needed the quantify query syntax this is the branch I sent to Galois for use in CP7. I've closed the PR but will keep the branch around since they need to pull from it.

**Pull request closed without merging**
